### PR TITLE
Added table of models supported.

### PR DESCRIPTION
**Pull request by D-Jeffrey**
Rounding out the documentation

### CODE REVIEW

**Comment by D-Jeffrey** [comment]
Hmm... still figuring out this git thing, not sure how to only give the one Push

**Comment by crowbarz** [comment]
Not quite sure what you mean by "give the one push"?

I'm no git expert myself, but basically this PR will track all commits you have pushed/will push into https://github.com/D-Jeffrey/ha-pioneer_async . If you are looking to put a second commit into a different PR, then you need to create a separate branch in your fork and commit those changes into that branch instead, then raise another PR from that branch.

**Comment by D-Jeffrey** [comment]
I just wanted you to have the choice to include/accept the two edits as separate actions.

**Comment by crowbarz** [comment]
Ok, yeah in the future you will need to put each into separate PRs to accomplish that. I haven't looked at the changes in detail yet but it's probably ok to leave them both in the same PR, although please update the PR title/description to reflect both changes

**Comment by D-Jeffrey** [comment]
If I close this does it cancel the Pull request?

**Pull request closed without merging**
