### PR TITLE
address some minor pylint issues raised by running HA's linter

### PR DESCRIPTION
**Pull request by mikey0000**

### CODE REVIEW

**Comment by crowbarz** [comment]
I am fine with the type annotation changes (thanks) but I don't get or agree with the need to capitalise the first letter of strings passed to logging. In some cases (eg. `Unload_entry` vs `unload_entry`) it is actually wrong to capitalise because this refers to an HA function name which is itself not capitalised. Do you know which tool is making that change? The [HA Style Guidelines](https://developers.home-assistant.io/docs/development_guidelines) says nothing about the requirement to capitalise all logging strings, in fact the suggestion to remove periods from the end of logging strings indicates that these are not supposed to be considered as whole sentences.

Also, for now, I am intentionally ignoring the reserved nature of `_LOGGER.info` as it is very useful for providing a less verbose level of debug than `_LOGGER.debug`.

**Comment by mikey0000** [comment]
It was pylint which gave the error within the dev container. I'm not going to object to changing it back. I'll go check whether it was the default pylint or HAs on thst one.

10/03/2023 8:14:56 am Crowbar Z ***@***.***>:

**Comment by mikey0000** [comment]
Also the broad exceptions could use # pylint: disable=broad-except

**Comment by mikey0000** [comment]
changed the logger text back

**Pull request merged**
